/*
 * SPDX-License-Identifier: 0BSD
 *
 * Generate dash's signal-name lookup without the upstream GNU Bash helper.
 * Signal names and numbers are platform ABI facts; this implementation was
 * written independently for Xmin's bundled Unix shell build.
 */
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>

#ifndef NSIG
# define NSIG 64
#endif

static const char *names[NSIG];
static char numeric_names[NSIG][24];
#if defined(SIGRTMIN) && defined(SIGRTMAX)
static char realtime_names[NSIG][24];
#endif

static void
set_name(int number, const char *name)
{
	if (number >= 0 && number < NSIG)
		names[number] = name;
}

static void
initialize_names(void)
{
	int signal_number;
	for (signal_number = 0; signal_number < NSIG; ++signal_number) {
		snprintf(numeric_names[signal_number],
		         sizeof(numeric_names[signal_number]), "%d", signal_number);
		names[signal_number] = numeric_names[signal_number];
	}
	set_name(0, "EXIT");

#define XMIN_SIGNAL(symbol, text) set_name(symbol, text)
#ifdef SIGHUP
	XMIN_SIGNAL(SIGHUP, "HUP");
#endif
#ifdef SIGINT
	XMIN_SIGNAL(SIGINT, "INT");
#endif
#ifdef SIGQUIT
	XMIN_SIGNAL(SIGQUIT, "QUIT");
#endif
#ifdef SIGILL
	XMIN_SIGNAL(SIGILL, "ILL");
#endif
#ifdef SIGTRAP
	XMIN_SIGNAL(SIGTRAP, "TRAP");
#endif
#ifdef SIGIOT
	XMIN_SIGNAL(SIGIOT, "IOT");
#endif
#ifdef SIGABRT
	XMIN_SIGNAL(SIGABRT, "ABRT");
#endif
#ifdef SIGEMT
	XMIN_SIGNAL(SIGEMT, "EMT");
#endif
#ifdef SIGFPE
	XMIN_SIGNAL(SIGFPE, "FPE");
#endif
#ifdef SIGKILL
	XMIN_SIGNAL(SIGKILL, "KILL");
#endif
#ifdef SIGBUS
	XMIN_SIGNAL(SIGBUS, "BUS");
#endif
#ifdef SIGSEGV
	XMIN_SIGNAL(SIGSEGV, "SEGV");
#endif
#ifdef SIGSYS
	XMIN_SIGNAL(SIGSYS, "SYS");
#endif
#ifdef SIGPIPE
	XMIN_SIGNAL(SIGPIPE, "PIPE");
#endif
#ifdef SIGALRM
	XMIN_SIGNAL(SIGALRM, "ALRM");
#endif
#ifdef SIGTERM
	XMIN_SIGNAL(SIGTERM, "TERM");
#endif
#ifdef SIGURG
	XMIN_SIGNAL(SIGURG, "URG");
#endif
#ifdef SIGSTOP
	XMIN_SIGNAL(SIGSTOP, "STOP");
#endif
#ifdef SIGTSTP
	XMIN_SIGNAL(SIGTSTP, "TSTP");
#endif
#ifdef SIGCONT
	XMIN_SIGNAL(SIGCONT, "CONT");
#endif
#ifdef SIGCLD
	XMIN_SIGNAL(SIGCLD, "CLD");
#endif
#ifdef SIGCHLD
	XMIN_SIGNAL(SIGCHLD, "CHLD");
#endif
#ifdef SIGTTIN
	XMIN_SIGNAL(SIGTTIN, "TTIN");
#endif
#ifdef SIGTTOU
	XMIN_SIGNAL(SIGTTOU, "TTOU");
#endif
#ifdef SIGPOLL
	XMIN_SIGNAL(SIGPOLL, "POLL");
#endif
#ifdef SIGIO
	XMIN_SIGNAL(SIGIO, "IO");
#endif
#ifdef SIGXCPU
	XMIN_SIGNAL(SIGXCPU, "XCPU");
#endif
#ifdef SIGXFSZ
	XMIN_SIGNAL(SIGXFSZ, "XFSZ");
#endif
#ifdef SIGVTALRM
	XMIN_SIGNAL(SIGVTALRM, "VTALRM");
#endif
#ifdef SIGPROF
	XMIN_SIGNAL(SIGPROF, "PROF");
#endif
#ifdef SIGWINCH
	XMIN_SIGNAL(SIGWINCH, "WINCH");
#endif
#ifdef SIGINFO
	XMIN_SIGNAL(SIGINFO, "INFO");
#endif
#ifdef SIGUSR1
	XMIN_SIGNAL(SIGUSR1, "USR1");
#endif
#ifdef SIGUSR2
	XMIN_SIGNAL(SIGUSR2, "USR2");
#endif
#ifdef SIGPWR
	XMIN_SIGNAL(SIGPWR, "PWR");
#endif
#ifdef SIGLOST
	XMIN_SIGNAL(SIGLOST, "LOST");
#endif
#undef XMIN_SIGNAL

#if defined(SIGRTMIN) && defined(SIGRTMAX)
	if (SIGRTMIN >= 0 && SIGRTMAX < NSIG && SIGRTMIN <= SIGRTMAX) {
		const int midpoint = (SIGRTMIN + SIGRTMAX) / 2;
		for (signal_number = SIGRTMIN; signal_number <= SIGRTMAX;
		     ++signal_number) {
			if (signal_number == SIGRTMIN)
				snprintf(realtime_names[signal_number], 24, "RTMIN");
			else if (signal_number == SIGRTMAX)
				snprintf(realtime_names[signal_number], 24, "RTMAX");
			else if (signal_number <= midpoint)
				snprintf(realtime_names[signal_number], 24, "RTMIN+%d",
				         signal_number - SIGRTMIN);
			else
				snprintf(realtime_names[signal_number], 24, "RTMAX-%d",
				         SIGRTMAX - signal_number);
			names[signal_number] = realtime_names[signal_number];
		}
	}
#endif
}

int
main(int argc, char **argv)
{
	FILE *output;
	int signal_number;
	if (argc > 2) {
		fprintf(stderr, "usage: %s [output-file]\n", argv[0]);
		return 2;
	}
	output = argc == 2 ? fopen(argv[1], "w") : fopen("signames.c", "w");
	if (!output) {
		perror("cannot create signal-name table");
		return 1;
	}
	initialize_names();
	fputs("/* Generated by Xmin's 0BSD dash-mksignames.c. */\n"
	      "#include <signal.h>\n\n"
	      "const char *const signal_names[NSIG + 1] = {\n", output);
	for (signal_number = 0; signal_number < NSIG; ++signal_number)
		fprintf(output, "    \"%s\",\n", names[signal_number]);
	fputs("    (char *)0x0\n};\n", output);
	return fclose(output) == 0 ? 0 : 1;
}
