#!/usr/bin/env python3
"""Generate the committed CMake source allowlist from pinned OSMesa metadata."""

from __future__ import annotations

import argparse
import pathlib
import re


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("upstream_cmake", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    text = args.upstream_cmake.read_text(encoding="utf-8")
    match = re.search(r"set\(osmesa_srcs\s*\n(?P<body>.*?)^\s*\)", text,
                      flags=re.MULTILINE | re.DOTALL)
    if match is None:
        raise SystemExit("could not locate set(osmesa_srcs ...) in upstream CMake")

    sources = []
    for line in match.group("body").splitlines():
        source = line.strip()
        if not source or source.startswith("#"):
            continue
        if not source.endswith(".c") or any(character.isspace() for character in source):
            raise SystemExit(f"unexpected OSMesa source-list entry: {source!r}")
        if not (args.upstream_cmake.parent / source).is_file():
            raise SystemExit(f"OSMesa source is missing: {source}")
        sources.append(source)

    if len(sources) != 171 or len(sources) != len(set(sources)):
        raise SystemExit(f"expected 171 unique OSMesa sources, found {len(sources)}")

    output = [
        "# Generated by tools/generate-osmesa-sources.py; do not edit by hand.",
        "set(xmin_osmesa_source_files",
    ]
    output.extend(f"  {source}" for source in sources)
    output.extend((")", ""))
    args.output.write_text("\n".join(output), encoding="utf-8")


if __name__ == "__main__":
    main()
