#!/usr/bin/env python3
"""Convert libXfont2's pinned gzip arrays to uncompressed C resources."""

import argparse
import gzip
import hashlib
import pathlib
import re


FONT_NAMES = ("6x13", "cursor")


def extract_compressed(source: str, name: str) -> bytes:
    match = re.search(
        rf"static const char file_{re.escape(name)}\[\] = \{{(.*?)\n\}};",
        source,
        re.DOTALL,
    )
    if not match:
        raise ValueError(f"could not find file_{name} in upstream fonts.c")
    octets = re.findall(r"'\\([0-7]{1,3})'", match.group(1))
    if not octets:
        raise ValueError(f"file_{name} contains no octal byte literals")
    return bytes(int(octet, 8) for octet in octets)


def emit_array(output, name: str, data: bytes) -> None:
    output.write(f"static const char file_{name}[] = {{\n")
    for offset in range(0, len(data), 12):
        values = ", ".join(f"'\\{value:03o}'" for value in data[offset:offset + 12])
        output.write(f"    {values},\n")
    output.write("};\n\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("upstream_fonts_c", type=pathlib.Path)
    parser.add_argument("output_c", type=pathlib.Path)
    args = parser.parse_args()

    source = args.upstream_fonts_c.read_text(encoding="ascii")
    fonts = {
        name: gzip.decompress(extract_compressed(source, name))
        for name in FONT_NAMES
    }

    args.output_c.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.output_c.with_suffix(args.output_c.suffix + ".tmp")
    with temporary.open("w", encoding="ascii", newline="\n") as output:
        output.write("/* Generated by tools/generate-builtin-fonts.py from "
                     "libXfont2 2.0.8; do not edit. */\n")
        for name in FONT_NAMES:
            digest = hashlib.sha256(fonts[name]).hexdigest()
            output.write(f"/* {name}.pcf: {len(fonts[name])} bytes, sha256 {digest} */\n")
        output.write('#include "builtin.h"\n\n')
        for name in ("cursor", "6x13"):
            emit_array(output, name, fonts[name])
        output.write(
            'static char name_6x13[] = "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-1";\n'
            'static char name_cursor[] = "cursor";\n\n'
            'const BuiltinFileRec builtin_files[] = {\n'
            '    { "6x13.builtin", sizeof file_6x13, file_6x13 },\n'
            '    { "cursor.builtin", sizeof file_cursor, file_cursor }\n'
            '};\n\n'
            'const int builtin_files_count = sizeof builtin_files / sizeof builtin_files[0];\n\n'
            'const BuiltinDirRec builtin_dir[] = {\n'
            '    { "6x13.builtin", name_6x13 },\n'
            '    { "cursor.builtin", name_cursor }\n'
            '};\n\n'
            'const int builtin_dir_count = sizeof builtin_dir / sizeof builtin_dir[0];\n\n'
            'static char alias_fixed[] = "fixed";\n'
            'static char alias_6x13[] = "6x13";\n'
            'static char alias_6x13_100[] = "-misc-fixed-medium-r-semicondensed--13-100-100-100-c-60-iso8859-1";\n\n'
            'const BuiltinAliasRec builtin_alias[] = {\n'
            '    { alias_fixed, name_6x13 },\n'
            '    { alias_6x13, name_6x13 },\n'
            '    { alias_6x13_100, name_6x13 }\n'
            '};\n\n'
            'const int builtin_alias_count = sizeof builtin_alias / sizeof builtin_alias[0];\n'
        )
    temporary.replace(args.output_c)


if __name__ == "__main__":
    main()
