#!/usr/bin/env python3
"""Generate Xmin's normalized X11 named-color lookup table."""

from __future__ import annotations

import argparse
import pathlib
import re


COLOR_LINE = re.compile(
    r"^\s*(?P<red>\d+)\s+(?P<green>\d+)\s+(?P<blue>\d+)\s+"
    r"(?P<name>.*?)\s*$"
)


def parse_color_database(path: pathlib.Path) -> dict[str, int]:
    colors: dict[str, int] = {}
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        if not raw_line.strip() or raw_line.lstrip().startswith("!"):
            continue
        match = COLOR_LINE.match(raw_line)
        if match is None:
            raise ValueError(f"{path}:{line_number}: malformed color entry")
        channels = tuple(
            int(match.group(channel)) for channel in ("red", "green", "blue")
        )
        if any(channel > 255 for channel in channels):
            raise ValueError(f"{path}:{line_number}: channel exceeds 255")
        name = "".join(match.group("name").lower().split())
        if not name:
            raise ValueError(f"{path}:{line_number}: empty color name")
        value = (channels[0] << 16) | (channels[1] << 8) | channels[2]
        previous = colors.setdefault(name, value)
        if previous != value:
            raise ValueError(
                f"{path}:{line_number}: conflicting values for normalized name {name!r}"
            )
    return colors


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    colors = parse_color_database(args.input)
    lines = [
        "/*",
        " * Generated by tools/generate-x11-colors.py from X.Org rgb.txt.",
        " * Names are lowercase with whitespace removed; values are packed RGB8.",
        " */",
    ]
    lines.extend(
        f'    {{"{name}", 0x{value:06x}U}},'
        for name, value in sorted(colors.items())
    )
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
