#!/bin/sh
# Regenerate Xmin's compiled-in US keyboard map for maintenance imports.
set -eu

if [ "$#" -ne 2 ]; then
    echo "usage: $0 /path/to/xkeyboard-config-2.47 output-header" >&2
    exit 2
fi

xkeyboard_config_dir=$1
output_header=$2
input_file=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)/data/xkb/xmin-us.xkb

case $output_header in
    /*) ;;
    *) output_header=$(pwd)/$output_header ;;
esac
xkm_file=${output_header}.xkm.$$
generated_header=${output_header}.generated.$$

trap 'rm -f "$xkm_file" "$generated_header"' EXIT HUP INT TERM

if [ ! -d "$xkeyboard_config_dir/keycodes" ] || \
   [ ! -d "$xkeyboard_config_dir/symbols" ]; then
    echo "error: not an extracted xkeyboard-config source tree: $xkeyboard_config_dir" >&2
    exit 1
fi

if ! command -v xkbcomp >/dev/null 2>&1; then
    echo "error: xkbcomp is required only to regenerate the embedded map" >&2
    exit 1
fi

mkdir -p "$(dirname -- "$output_header")"
xkbcomp -w 1 -xkm -R"$xkeyboard_config_dir" "$input_file" "$xkm_file"

{
    echo "/* Generated by tools/generate-xkb-map.sh; do not edit. */"
    echo "#ifndef XMIN_US_MAP_H"
    echo "#define XMIN_US_MAP_H"
    echo
    echo "static unsigned char xmin_us_xkm[] = {"
    od -An -v -tx1 "$xkm_file" | awk '{
        printf "    "
        for (i = 1; i <= NF; ++i)
            printf "0x%s,%s", $i, (i == NF ? "" : " ")
        printf "\n"
    }'
    echo "};"
    echo
    echo "#endif"
} > "$generated_header"

mv "$generated_header" "$output_header"
trap - EXIT HUP INT TERM
rm -f "$xkm_file"
