#!/bin/sh

set -eu

if [ "$#" -ne 10 ]; then
    echo "usage: $0 libxcb xcb-proto xcb-util xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-cursor xcb-util-wm libxkbcommon libXau" >&2
    exit 2
fi

libxcb=$1
xcbproto=$2
xcbutil=$3
xcbimage=$4
xcbkeysyms=$5
xcbrenderutil=$6
xcbcursor=$7
xcbwm=$8
xkbcommon=$9
shift 9
xau=$1
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

require_file()
{
    if [ ! -f "$1" ]; then
        echo "required upstream file is missing: $1" >&2
        exit 2
    fi
}

require_file "$libxcb/src/c_client.py"
require_file "$xcbproto/src/xkb.xml"
require_file "$xcbutil/src/xcb_aux.c"
require_file "$xcbimage/image/xcb_image.c"
require_file "$xcbkeysyms/keysyms/keysyms.c"
require_file "$xcbrenderutil/renderutil/cache.c"
require_file "$xcbcursor/cursor/shape_to_id.c"
require_file "$xcbwm/icccm/icccm.c"
require_file "$xkbcommon/src/xkbcomp/parser.y"
require_file "$xau/AuGetBest.c"

# Keep the server automation subset and the Qt client copy generated by the
# same pinned libxcb/xcb-proto pair.
"$root/tools/import-libxcb.sh" "$libxcb" "$xcbproto"

generated=$(mktemp -d "${TMPDIR:-/tmp}/xmin-qt-client.XXXXXX")
trap 'rm -rf "$generated"' EXIT HUP INT TERM

protocols="randr shm sync xkb"
(
    cd "$generated"
    for protocol in $protocols; do
        PYTHONDONTWRITEBYTECODE=1 python3 "$libxcb/src/c_client.py" \
            -c "libxcb 1.17.0" -l X -s 3 -p "$xcbproto" \
            "$xcbproto/src/$protocol.xml"
    done
)

for source in xcb_util.c xcb_auth.c; do
    cp -p "$libxcb/src/$source" "$root/third_party/libxcb/src/$source"
done
for protocol in $protocols; do
    cp -p "$generated/$protocol.c" "$root/third_party/libxcb/src/$protocol.c"
    cp -p "$generated/$protocol.h" "$root/third_party/libxcb/include/xcb/$protocol.h"
done

install -d "$root/third_party/xcb-util/src" \
    "$root/third_party/xcb-util/include/xcb"
for source in atoms.c event.c xcb_aux.c; do
    cp -p "$xcbutil/src/$source" "$root/third_party/xcb-util/src/$source"
done
for header in xcb_util.h xcb_atom.h xcb_aux.h xcb_event.h; do
    cp -p "$xcbutil/src/$header" "$root/third_party/xcb-util/include/xcb/$header"
done
cp -p "$xcbimage/image/xcb_image.c" "$root/third_party/xcb-util/src/xcb_image.c"
for header in xcb_image.h xcb_pixel.h xcb_bitops.h; do
    cp -p "$xcbimage/image/$header" "$root/third_party/xcb-util/include/xcb/$header"
done
cp -p "$xcbkeysyms/keysyms/keysyms.c" "$root/third_party/xcb-util/src/xcb_keysyms.c"
cp -p "$xcbkeysyms/keysyms/xcb_keysyms.h" \
    "$root/third_party/xcb-util/include/xcb/xcb_keysyms.h"
for source in cache.c util.c glyph.c; do
    cp -p "$xcbrenderutil/renderutil/$source" \
        "$root/third_party/xcb-util/src/renderutil_$source"
done
cp -p "$xcbrenderutil/renderutil/xcb_renderutil.h" \
    "$root/third_party/xcb-util/include/xcb/xcb_renderutil.h"
for source in cursor.c shape_to_id.c load_cursor.c parse_cursor_file.c; do
    cp -p "$xcbcursor/cursor/$source" \
        "$root/third_party/xcb-util/src/cursor_$source"
done
cp -p "$xcbcursor/cursor/cursor.h" "$root/third_party/xcb-util/src/cursor.h"
cp -p "$xcbcursor/cursor/xcb_cursor.h" \
    "$root/third_party/xcb-util/include/xcb/xcb_cursor.h"
cp -p "$xcbwm/icccm/icccm.c" "$root/third_party/xcb-util/src/xcb_icccm.c"
cp -p "$xcbwm/icccm/xcb_icccm.h" \
    "$root/third_party/xcb-util/include/xcb/xcb_icccm.h"

install -d "$root/third_party/libxkbcommon/include/xkbcommon" \
    "$root/third_party/libxkbcommon/src/compose" \
    "$root/third_party/libxkbcommon/src/xkbcomp" \
    "$root/third_party/libxkbcommon/src/x11"
for header in xkbcommon.h xkbcommon-compat.h xkbcommon-compose.h \
        xkbcommon-keysyms.h xkbcommon-names.h xkbcommon-x11.h; do
    cp -p "$xkbcommon/include/xkbcommon/$header" \
        "$root/third_party/libxkbcommon/include/xkbcommon/$header"
done

xkb_core_files="
atom.c atom.h context.c context.h context-priv.c darray.h keysym.c keysym.h
keysym-case-mappings.c keysym-utf.c ks_tables.h keymap.c keymap.h
keymap-compare.c keymap-compare.h keymap-priv.c messages-codes.h rmlvo.c
rmlvo.h scanner-utils.c scanner-utils.h state.c text.c text.h utf8.c utf8.h
utf8-decoding.c utf8-decoding.h utils.c utils.h util-mem.h
utils-checked-arithmetic.h utils-numbers.h utils-paths.c utils-paths.h
"
for file in $xkb_core_files; do
    cp -p "$xkbcommon/src/$file" "$root/third_party/libxkbcommon/src/$file"
done

xkb_compose_files="
constants.h parser.c parser.h paths.c paths.h state.c table.c table.h
"
for file in $xkb_compose_files; do
    cp -p "$xkbcommon/src/compose/$file" \
        "$root/third_party/libxkbcommon/src/compose/$file"
done

xkbcomp_files="
action.c action.h ast.h ast-build.c ast-build.h compat.c expr.c expr.h
include.c include.h keycodes.c keymap.c keymap-dump.c keywords.c
parser-priv.h rules.c rules.h scanner.c symbols.c types.c vmod.c vmod.h
xkbcomp.c xkbcomp-priv.h
"
for file in $xkbcomp_files; do
    cp -p "$xkbcommon/src/xkbcomp/$file" \
        "$root/third_party/libxkbcommon/src/xkbcomp/$file"
done
(
    cd "$generated"
    bison --defines=parser.h -o parser.c -p _xkbcommon_ \
        "$xkbcommon/src/xkbcomp/parser.y"
)
cp -p "$generated/parser.c" "$generated/parser.h" \
    "$root/third_party/libxkbcommon/src/xkbcomp/"
for file in keymap.c state.c util.c x11-priv.h; do
    cp -p "$xkbcommon/src/x11/$file" \
        "$root/third_party/libxkbcommon/src/x11/$file"
done

for source in AuDispose.c AuFileName.c AuGetBest.c AuRead.c; do
    cp -p "$xau/$source" "$root/third_party/libXau/$source"
done

install -d "$root/LICENSES/xcb-util" "$root/LICENSES/xcb-util-image" \
    "$root/LICENSES/xcb-util-keysyms" "$root/LICENSES/xcb-util-renderutil" \
    "$root/LICENSES/xcb-util-cursor" "$root/LICENSES/xcb-util-wm" \
    "$root/LICENSES/libxkbcommon"
cp -p "$xcbutil/COPYING" "$root/LICENSES/xcb-util/COPYING"
cp -p "$xcbimage/COPYING" "$root/LICENSES/xcb-util-image/COPYING"
cp -p "$xcbkeysyms/COPYING" "$root/LICENSES/xcb-util-keysyms/COPYING"
cp -p "$xcbrenderutil/COPYING" "$root/LICENSES/xcb-util-renderutil/COPYING"
cp -p "$xcbcursor/COPYING" "$root/LICENSES/xcb-util-cursor/COPYING"
cp -p "$xcbwm/COPYING" "$root/LICENSES/xcb-util-wm/COPYING"
cp -p "$xkbcommon/LICENSE" "$root/LICENSES/libxkbcommon/LICENSE"
cp -p "$xau/COPYING" "$root/LICENSES/libXau/COPYING"

echo "Imported the pinned XCB utility, xkbcommon, and X authority Qt client closure."
