if(NOT DEFINED XMIN_FONT_DIRECTORY OR NOT DEFINED XMIN_FONT_OUTPUT)
  message(FATAL_ERROR
    "EmbedGoFonts.cmake requires XMIN_FONT_DIRECTORY and XMIN_FONT_OUTPUT"
  )
endif()

set(font_files
  Go-Regular.ttf
  Go-Bold.ttf
  Go-Italic.ttf
  Go-Bold-Italic.ttf
  Go-Mono.ttf
  Go-Mono-Bold.ttf
  Go-Mono-Italic.ttf
  Go-Mono-Bold-Italic.ttf
)
set(font_symbols
  go_regular
  go_bold
  go_italic
  go_bold_italic
  go_mono
  go_mono_bold
  go_mono_italic
  go_mono_bold_italic
)

file(WRITE "${XMIN_FONT_OUTPUT}"
  "// Generated by cmake/EmbedGoFonts.cmake; do not edit.\n"
  "#include \"embedded_fonts.hpp\"\n\n"
  "#include <cstdlib>\n\n"
  "namespace xmin::client::font {\nnamespace {\n"
)

list(LENGTH font_files font_count)
math(EXPR font_last "${font_count} - 1")
foreach(index RANGE ${font_last})
  list(GET font_files ${index} filename)
  list(GET font_symbols ${index} symbol)
  set(source "${XMIN_FONT_DIRECTORY}/${filename}")
  if(NOT EXISTS "${source}")
    message(FATAL_ERROR "Missing embedded font input: ${source}")
  endif()

  file(READ "${source}" font_hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," font_bytes
    "${font_hex}"
  )
  string(REGEX REPLACE
    "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" font_bytes
    "${font_bytes}"
  )
  file(APPEND "${XMIN_FONT_OUTPUT}"
    "alignas(4) constexpr unsigned char ${symbol}[] = {\n"
    "${font_bytes}\n};\n\n"
  )
endforeach()

file(APPEND "${XMIN_FONT_OUTPUT}"
  "} // namespace\n\n"
  "EmbeddedFontBlob embedded_font(EmbeddedFace face) noexcept\n"
  "{\n"
  "    switch (face) {\n"
  "    case EmbeddedFace::sans_regular:\n"
  "        return {go_regular, sizeof(go_regular)};\n"
  "    case EmbeddedFace::sans_bold:\n"
  "        return {go_bold, sizeof(go_bold)};\n"
  "    case EmbeddedFace::sans_italic:\n"
  "        return {go_italic, sizeof(go_italic)};\n"
  "    case EmbeddedFace::sans_bold_italic:\n"
  "        return {go_bold_italic, sizeof(go_bold_italic)};\n"
  "    case EmbeddedFace::mono_regular:\n"
  "        return {go_mono, sizeof(go_mono)};\n"
  "    case EmbeddedFace::mono_bold:\n"
  "        return {go_mono_bold, sizeof(go_mono_bold)};\n"
  "    case EmbeddedFace::mono_italic:\n"
  "        return {go_mono_italic, sizeof(go_mono_italic)};\n"
  "    case EmbeddedFace::mono_bold_italic:\n"
  "        return {go_mono_bold_italic, sizeof(go_mono_bold_italic)};\n"
  "    }\n"
  "    std::abort();\n"
  "}\n\n"
  "} // namespace xmin::client::font\n"
)
